site_name: MAS GitOps (test)
site_url: https://pages.github.com/tomklapiscak/mkdocsmike

repo_name: GitHub
repo_url: https://github.com/tomklapiscak/mkdocsmike
edit_uri: blob/main/docs/

nav:
  - 'Home': index.md
  - 'Architecture': 
    - 'Overview': 'architecture.md'
    - 'The Source Repository': helmcharts.md
    - 'The Config Repository': configrepo.md
    - 'The Secrets Vault': secrets.md
  
  - 'Details':
    - 'Mapping Config to MAS Deployments': configtoinstances.md
    - 'Deployment Orchestration': orchestration.md
    
  - 'Reference':
    - 'Account Root Application Manifest': accountrootmanifest.md
    - 'Known Limitations': limitations.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
  features:
    - content.code.annotate
extra_css:
  - extra.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

plugins:
  - macros
  - drawio_file

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - attr_list
  - markdown.extensions.footnotes
